import { ArrowLeft, ArrowRight, Save } from "lucide-react";
import { useEffect, useState } from "react";
import { AppShell } from "../../components/layout/AppShell";
import { getTopic, getUserExam, saveProgress } from "../../lib/data";
import { navigate } from "../../app/router";
import type { SessionUser, AppExam } from "../../types/app";

export function Topic({ user, topicId }: { user: SessionUser; topicId: string }) {
  const [exam, setExam] = useState<AppExam | null>(null); const [data, setData] = useState<any>(null); const [status, setStatus] = useState<any>("not_started"); const [confidence, setConfidence] = useState<number | null>(null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { (async () => { try { const current = await getUserExam(user.id); if (!current) { navigate("/exam-setup"); return; } const detail = await getTopic(user.id, current.variantId, topicId); if (!detail) { navigate("/syllabus"); return; } setExam(current); setData(detail); setStatus(detail.topic.status); setConfidence(detail.topic.confidence); } catch (err) { setMessage(err instanceof Error ? err.message : "Unable to load topic."); } })(); }, [user.id, topicId]);
  async function persist(nextStatus: "not_started"|"in_progress"|"completed" = status) { setSaving(true); setMessage(""); try { await saveProgress(user.id, topicId, nextStatus, confidence); setStatus(nextStatus); setMessage("Progress saved"); } catch (err) { setMessage(err instanceof Error ? err.message : "Unable to save progress."); } finally { setSaving(false); } }
  if (!data) return <div className="boot">Loading topic…</div>;
  const content = data.content;
  return <AppShell user={user} active="syllabus"><div className="lesson"><div className="lessonTop"><button className="backPlain" onClick={() => navigate("/syllabus")}><ArrowLeft/>Back to syllabus</button><div className="lessonNav"><button disabled={!data.previous} onClick={() => data.previous && navigate(`/topic/${data.previous.id}`)}><ArrowLeft/>Previous</button><button disabled={!data.next} onClick={() => data.next && navigate(`/topic/${data.next.id}`)}>Next<ArrowRight/></button></div></div><div className="lessonIntro"><span>UNIT {data.unit.unitNumber} · TOPIC {data.topic.topicNumber}</span><h1>{data.topic.title}</h1><p>{exam?.examName} · {exam?.subject}</p></div><div className="lessonGrid"><article className="lessonBody">{content ? <><div className="objectives"><h3>What you'll learn</h3><ul>{(content.learning_objectives || []).map((item:string) => <li key={item}>{item}</li>)}</ul></div><div className="markdown">{String(content.lesson_markdown || "").split("\n").map((line:string, i:number) => line.startsWith("## ") ? <h2 key={i}>{line.slice(3)}</h2> : line.startsWith("### ") ? <h3 key={i}>{line.slice(4)}</h3> : line.startsWith("- ") ? <li key={i}>{line.slice(2)}</li> : line.trim() ? <p key={i}>{line}</p> : null)}</div><div className="terms"><h3>Key terms</h3>{(Array.isArray(content.key_terms) ? content.key_terms : []).map((item:any) => <div key={item.term}><strong>{item.term}</strong><span>{item.meaning}</span></div>)}</div></> : <div className="emptyState">Detailed lesson content is not published for this topic yet.</div>}</article><aside className="lessonSide"><div className="progressBox"><span>YOUR PROGRESS</span><h3>{status.replace("_", " ")}</h3><div className="statusButtons"><button className={status === "in_progress" ? "chosen" : ""} onClick={() => persist("in_progress")} disabled={saving}>In progress</button><button className={status === "completed" ? "chosen" : ""} onClick={() => persist("completed")} disabled={saving}>Completed</button></div><span>Confidence</span><div className="confidence">{[1,2,3,4,5].map(n => <button key={n} className={confidence === n ? "chosen" : ""} onClick={() => setConfidence(n)}>{n}</button>)}</div><button className="saveBtn" onClick={() => persist(status)} disabled={saving}><Save/>{saving ? "Saving…" : "Save progress"}</button>{message && <small className="saveMessage">{message}</small>}</div><div className="lessonMeta"><span>ESTIMATED</span><strong>{content?.estimated_minutes ?? "—"} min</strong><span>DIFFICULTY</span><strong>{content?.difficulty ?? "—"}</strong></div></aside></div></div></AppShell>;
}
