import { ArrowLeft, Clock3, Pause, Play, RotateCcw, Save, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "../../components/layout/AppShell";
import { getSessions, getSyllabus, getUserExam, saveSession } from "./session.service";
import { navigate } from "../../app/router";
import type { SessionUser, AppExam } from "../../types/app";

const format = (seconds: number) => `${String(Math.floor(seconds / 3600)).padStart(2, "0")}:${String(Math.floor((seconds % 3600) / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;

export function Sessions({ user }: { user: SessionUser }) {
  const [exam, setExam] = useState<AppExam | null>(null); const [topics, setTopics] = useState<any[]>([]); const [history, setHistory] = useState<any[]>([]); const [topicId, setTopicId] = useState(""); const [elapsed, setElapsed] = useState(0); const [running, setRunning] = useState(false); const [accumulated, setAccumulated] = useState(0); const [runStartedAt, setRunStartedAt] = useState<number | null>(null); const [sessionStartedAt, setSessionStartedAt] = useState<number | null>(null); const [notes, setNotes] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);

  useEffect(() => { (async () => { try { const current = await getUserExam(user.id); if (!current) { navigate("/exam-setup"); return; } setExam(current); const syllabus = await getSyllabus(user.id, current.variantId); setTopics(syllabus.flatMap((unit:any) => unit.topics.map((topic:any) => ({ ...topic, unitNumber: unit.unitNumber })))); setHistory(await getSessions(user.id, current.variantId)); } catch (err) { setMessage(err instanceof Error ? err.message : "Unable to load sessions."); } })(); }, [user.id]);

  useEffect(() => { if (!running || runStartedAt === null) return; const tick = () => setElapsed(accumulated + Math.floor((Date.now() - runStartedAt) / 1000)); tick(); const id = window.setInterval(tick, 1000); return () => window.clearInterval(id); }, [running, runStartedAt, accumulated]);
  const topicTitle = useMemo(() => topics.find(topic => topic.id === topicId)?.title, [topics, topicId]);
  const reset = () => { setRunning(false); setElapsed(0); setAccumulated(0); setRunStartedAt(null); setSessionStartedAt(null); setNotes(""); setMessage(""); };
  const leave = () => { if (running || elapsed > 0 || notes.trim()) { if (!window.confirm("Leave this session? Unsaved study time will be lost.")) return; } navigate("/dashboard"); };
  const start = () => { if (runStartedAt === null) { const now = Date.now(); setRunStartedAt(now); if (sessionStartedAt === null) setSessionStartedAt(now); } setRunning(true); };
  const pause = () => { if (runStartedAt !== null) { const next = accumulated + Math.floor((Date.now() - runStartedAt) / 1000); setAccumulated(next); setElapsed(next); setRunStartedAt(null); } setRunning(false); };
  async function save() { if (!exam || sessionStartedAt === null || elapsed < 1) { setMessage("Start the session before saving."); return; } setSaving(true); setMessage(""); try { if (running) pause(); const finalElapsed = runStartedAt !== null ? accumulated + Math.floor((Date.now() - runStartedAt) / 1000) : elapsed; const end = new Date().toISOString(); await saveSession(user.id, exam.variantId, topicId || null, finalElapsed, new Date(sessionStartedAt).toISOString(), end, notes); setHistory(await getSessions(user.id, exam.variantId)); setMessage("Study session saved"); reset(); } catch (err) { setMessage(err instanceof Error ? err.message : "Unable to save study session."); } finally { setSaving(false); } }

  return <AppShell user={user} active="sessions"><div className="sessionWrap"><header className="pageHead"><div><span>STUDY SESSIONS</span><h1>Study with intention.</h1><p>Focus on one topic and track the time.</p></div><div className="headerActions"><button onClick={() => navigate("/dashboard")}><ArrowLeft/>Back</button><button className="exit" onClick={leave}><X/>Exit</button></div></header><div className="sessionLayout"><section className="focusCard"><span>FOCUSED STUDY</span><h2>{topicTitle || "Choose a topic to begin"}</h2><select value={topicId} onChange={e => setTopicId(e.target.value)} disabled={running || saving}><option value="">Select syllabus topic</option>{topics.map(topic => <option key={topic.id} value={topic.id}>Unit {topic.unitNumber} · {topic.title}</option>)}</select><div className="timerBox"><strong>{format(elapsed)}</strong><span className={running ? "live" : ""}><i/> {running ? "Session in progress" : elapsed ? "Session paused" : "Ready to start"}</span></div><div className="timerActions"><button className="primary" onClick={start} disabled={!topicId || saving}><Play/>{elapsed ? "Resume" : "Start session"}</button><button onClick={pause} disabled={!running || saving}><Pause/>Pause</button><button onClick={reset} disabled={saving || (!elapsed && !notes)}><RotateCcw/>Reset</button></div><textarea placeholder="Optional notes — what did you cover, practise, or struggle with?" value={notes} onChange={e => setNotes(e.target.value)} disabled={saving}/><button className="saveBtn wide" onClick={save} disabled={saving || elapsed < 1}><Save/>{saving ? "Saving…" : "Save study session"}</button>{message && <div className="alert success">{message}</div>}</section><aside className="historyCard"><div className="historyHead"><div><span>YOUR ACTIVITY</span><h2>Recent sessions</h2></div><Clock3/></div>{history.length === 0 ? <div className="emptyState">Your saved sessions will appear here.</div> : history.map(session => <div className="historyRow" key={session.id}><div><strong>{session.topicTitle}</strong><small>{new Date(session.startedAt).toLocaleDateString()} · {new Date(session.startedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</small></div><b>{Math.round(session.durationSeconds / 60)} min</b></div>)}</aside></div></div></AppShell>;
}
